version: "3.1"
services:
    redis:
      image: redis:alpine
      container_name: app-redis
      ports:
        - "6379:6379"
    phpredisadmin:
      image: tehes/docker-phpredisadmin
      environment:
        - ADMIN_USER=admin
        - ADMIN_PASS=admin
        - REDIS_1_HOST=redis
        - REDIS_1_PORT=6379
      links:
        - redis
      ports:
        - "8082:80"
    postgres:
      image: postgres:9.5-alpine
      container_name: app-postgres
      restart: always
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=root
        - POSTGRES_DB=laravel
        - PGDATA=/var/lib/postgresql/data
      volumes:
         - db-data:/var/lib/postgresql/data
      ports:
       - "5432:5432"
      networks:
            testing_net:
                ipv4_address: 172.28.1.2
    pgadmin:
      image: dpage/pgadmin4
      container_name: pgadmin
      environment:
        PGADMIN_DEFAULT_EMAIL: "postgres"
        PGADMIN_DEFAULT_USERNAME: postgres
        PGADMIN_DEFAULT_PASSWORD: "root"
      ports:
        - "8088:80"

    webserver:
      image: nginx:alpine
      container_name: app-webserver
      working_dir: /application
      volumes:
          - ./application:/application
          - ./sourcefiles/nginx:/etc/nginx/conf.d
      ports:
       - "8089:8070"
      networks:
            testing_net:
                ipv4_address: 172.28.1.3

    php-fpm:
      build: sourcefiles/php-fpm
      container_name: app-php-fpm
      working_dir: /application
      volumes:
        - ./application:/application
        - ./sourcefiles/php-fpm/php-ini-overrides.ini:/etc/php/7.3/fpm/conf.d/99-overrides.ini
      networks:
          testing_net:
              ipv4_address: 172.28.1.4
networks:
    testing_net:
        ipam:
            driver: default
            config:
                - subnet: 172.28.0.0/16
volumes:
  db-data: